version: '3.8'

services:
  master:
    image: mysql:8.0
    container_name: master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    command: --server-id=1
    volumes:
      - master_data:/var/lib/mysql
      - ./init/master.sql:/docker-entrypoint-initdb.d/master.sql
    networks:
      - mysql_net
    ports:
      - "3306:3306"

  slave1:
    image: mysql:8.0
    container_name: slave1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    command: --server-id=2 --read-only=1
    volumes:
      - slave1_data:/var/lib/mysql
      - ./init/slave.sql:/docker-entrypoint-initdb.d/slave.sql

    networks:
      - mysql_net

  slave2:
    image: mysql:8.0
    container_name: slave2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    command: --server-id=3 --read-only=1  
    volumes:
      - slave2_data:/var/lib/mysql
      - ./init/slave.sql:/docker-entrypoint-initdb.d/slave.sql
    networks:
      - mysql_net

volumes:
  master_data:
  slave1_data:
  slave2_data:

networks:
  mysql_net:
